select*from Cleaned_Playstore_AppsF
select*from Cleaned_Playstore_reviewsF

/*(1)Which apps have the highest rating in the given available dataset?*/

Select App As Highly_Rated_Apps,max(Rating) As Ratings from Cleaned_Playstore_AppsF
where Rating = 5
group by App,Rating
order by Highly_Rated_Apps ASC

/*(2)What are the number of installs and reviews for the above apps? 
#Return the apps with the highest reviews to the top.*/

Select App As Highly_Reviewed_Apps,max(Reviews) As Reviews,Installs from Cleaned_Playstore_AppsF
where Rating = 5 
group by App,Reviews,Installs
order by Reviews DESC

/*(3)Which app has the highest number of reviews?
Also, mention the number of reviews and category of the app*/

Select Top 1 App,max(Reviews) As Number_of_reviews,Category from Cleaned_Playstore_AppsF
group by Category,App
Order by max(Reviews) Desc

/*(4)What is the total amount of revenue generated by the google play store by hosting apps? 
(Whenever a user buys apps  from the google play store, the amount is considered in the revenue)*/
 
Select Round(sum(Installs * Price),0) As Total_Revenue from Cleaned_Playstore_AppsF
where Type = 'Paid' 

/*(5)Which Category of google play store apps has the highest number of installs?
also, find out the total number of installs for that particular category.*/

Select Category,Sum(cast(Installs As bigint))As Number_of_Installs  From Cleaned_Playstore_AppsF
group by Category
Order by Sum(cast(Installs As bigint)) DESC

/*(6)Which Genre has the most number of published apps?*/

Select top 1 count(App) As Count_of_Published_Apps,Genres from  Cleaned_Playstore_AppsF
Group by Genres
Order by count(App) DESC

/*(7)Provide the list of all games ordered in such a way that 
the game that has the highest number of installs is displayed on the top
(to avoid duplicate results use distinct)*/

select Distinct App,max(Installs) As Highest_number_of_installs from  Cleaned_Playstore_AppsF
Where Category = 'Game'
group by App
Order by max(Installs) DESC

/*(8)Provide the list of apps that can work on android version 4.0.3 and UP.*/

Select App,Android_Ver from Cleaned_Playstore_AppsF
Where Android_Ver = '4.0.3 and up'

/*(9)How many apps from the given data set are free? Also, 
provide the number of paid apps.*/

Select Type,count(Type) As Count_FreeAndPaid_Apps
from Cleaned_Playstore_AppsF
group by Type 
Order by count(Type) DESC

/*(10)Which is the best dating app? 
(Best dating app is the one having the highest number of Reviews)*/

Select Top 1 App,max(Reviews) As highest_number_of_Reviews From Cleaned_Playstore_AppsF
where Category = 'DATING'
group by App
order by max(Reviews) DESC

/*(11)Get the number of reviews having positive sentiment and number of reviews 
having negative sentiment for the app  10 best foods for you and compare them.*/

Select App,Sentiment,Count(Sentiment) As Number_of_Reviews from Cleaned_Playstore_reviewsF
Where App = '10 Best Foods for You' AND Sentiment NOT IN ('Neutral')
Group by Sentiment,App
Order by Count(Sentiment) DESC
/*Having (Sentiment = 'Positive') AND (Sentiment = 'Negative')*/



/*(12)Which comments of ASUS SuperNote have sentiment polarity and sentiment subjectivity both as 1?*/

Select Translated_Review,Sentiment_Subjectivity,Sentiment_Polarity from  Cleaned_Playstore_reviewsF
Where App = 'ASUS SuperNote'
Group by App,Translated_Review,Sentiment_Subjectivity,Sentiment_Polarity
Having (Sentiment_Subjectivity = '1') AND (Sentiment_Polarity = '1')


/*(13)Get all the neutral sentiment reviews for the app Abs Training-Burn belly fat*/

Select Translated_Review,Sentiment from Cleaned_Playstore_reviewsF
Where App = 'Abs Training-Burn belly fat'
Group by App,Sentiment,Translated_Review
Having(Sentiment='Neutral')

/*(14)Extract all negative sentiment reviews for Adobe Acrobat Reader with their sentiment polarity
and sentiment subjectivity*/

Select Translated_Review,Sentiment_Polarity,Sentiment_Subjectivity from Cleaned_Playstore_reviewsF
where App = 'Adobe Acrobat Reader'
Group by App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
Having(Sentiment = 'Negative')


Select App,Reviews from Cleaned_Playstore_AppsF
where App = 'Facebook'
